version: '3.8'

services:
  cpy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:delegated
    working_dir: /app
    tty: true
    stdin_open: true
    command: bash

