name: Test and Release on Master Updates

on:
  pull_request:
    branches: [master]   # Run tests on PR targeting master
  push:
    branches: [master]    # Run tests and release on push to master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Build docker images
        run: docker compose build --no-cache
      - name: Run tests
        run: docker compose run --rm test

  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/master')
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract version
        id: get_version
        run: |
          VERSION=$(grep '^version' pyproject.toml | head -1 | cut -d '"' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=version::$VERSION"
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          body: Automatic release from merge to master
          draft: false
          prerelease: false

